### ISSUE TITLE
(Suggestion) Add transparent background

### ISSUE THREAD

**Issue by power-5000** [raiguard/Factorio-Tapeline#10]
Love the mod. I would love to see a transparent background fill. The default and light blue are best but with the grid covering things like belts it becomes hard to see them. I would love the option to disable or add a clear(transparent) color to the selection so you can turn certain parts of the grid off.

**Comment by raiguard** [comment]
You can customize the colors in the mod settings, including making parts of it transparent if you want. Just add / modify the `a` value in whatever colors you want to change.
