### ISSUE TITLE
Error while loading item prototype "tapeline-draw" (capsule) with BigBags mod active

### ISSUE THREAD

**Issue by Panderine** [raiguard/Factorio-Tapeline#11]
It says:
" stack_size"must be 1 when not-stackable is set.

Tapeline 1.0.4
BigBags 1.0.34

Does this fix belong here or to BigBags?

**Comment by Panderine** [comment]
Looking at the code I see stack_size already set to 1... so no idea where this is coming from.

**Comment by raiguard** [comment]
This is the fault of Big Bags. I have tried contacting the author of that mod several times, but have received no response. It's a badly designed mod that screws with stack sizes without giving a care. I would recommend using a different mod.

**Comment by Panderine** [comment]
Thank you for the fast response and sorry. Will look for another one :D
