### ISSUE TITLE
Tapeline v1.1.0 does not work ... on lab-tiles?

### ISSUE THREAD

**Issue by estebanthebad** [raiguard/Factorio-Tapeline#12]
I have a savegame, where tapeline does not work. Not as the only active mod and not together with other mods. TBH I don't really know why. Maybe because all the tiles are lab tiles? ( lab-dark-1, lab-dark-2, lab-white, https://wiki.factorio.com/Data.raw#tile ).

[blueprinting megamine.zip](https://github.com/raiguard/Factorio-Tapeline/files/4810479/blueprinting.megamine.zip)

**Comment by raiguard** [comment]
Thanks for the report, I'll have a patch out shortly to fix this.

The problem is that I accidentally used two different tick measurements - `tick` and `ticks_played` - to compare tilegrid drag logic. The fix was to use `ticks_played` everywhere.
