### ISSUE TITLE
edit tool crash

### ISSUE THREAD

**Issue by cloudziq** [raiguard/Factorio-Tapeline#13]
Hello.  There is a small crash when trying to edit a tile grid when there is already one edit-menu opened

reproduce:
draw a tile, switch to edit tool, select that tile (edit menu appears), switch to select tool again, and select that tile again - crash
![factorio_2020-07-08_23-44-08](https://user-images.githubusercontent.com/13541407/86976918-ce082580-c17b-11ea-9e21-36712c81612d.jpg)

Hope this helps,  I running Factorio 0.18.34 version and the latest version of the mod, also latest Flib :)

**Comment by raiguard** [comment]
Thanks, fixed for the next release. It should now be completely impossible to hold the edit tool while the editor GUI is open.

**Comment by raiguard** [comment]
The patch has been released.

**Comment by cloudziq** [comment]
great :)  thank you
