### ISSUE TITLE
error on load

### ISSUE THREAD

**Issue by Fr-Dae** [raiguard/Factorio-Tapeline#14]
Factorio 0.18.36
last version of tapeline
Lubuntu18.04x64
https://i.imgur.com/9wRfBtc.png
mods list https://pastebin.com/UGyWsfty

**Comment by raiguard** [comment]
Could you please provide the save file you experienced this on? Were you upgrading from a previous version of the mod when this occured?

**Comment by Fr-Dae** [comment]
could you contact me y discord ?
for the savegame
Dae#5125

**Comment by raiguard** [comment]
As per discussion on Discord, neither of us could reproduce it again. Closing.
