### ISSUE TITLE
Shortcut Bar button broken?

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-Tapeline#15]
#### Describe the Bug

When clicking on the Tapeline shortcut button from the Shortcut Bar nothing happens thus the Draw tool is not put in the cursor. 

#### To Reproduce

New game with no other mods loaded. Click Tapeline shortcut button.

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Save file: tapeline_error
Username: "Tealc."

[tapeline_error.zip](https://github.com/raiguard/Factorio-Tapeline/files/5012202/tapeline_error.zip)

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-Tapeline/files/5012201/factorio-current.log)

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by cloudziq** [comment]
I can confirm that shortcut button don't working with latest Flib, Tapeline and in Factorio version 0.18.45

**Comment by raiguard** [comment]
This is actually a bug in the base game, I've reported it to the developers. Thanks for the reports!

**Comment by raiguard** [comment]
So, an update: this isn't going to be fixed in the base game until after 1.0. There is a way to work around it in the meantime, so I'll do that for the next release.

**Comment by raiguard** [comment]
The patch has been released.

**Comment by Tealc-1899** [comment]
Thanks raiguard. Works great now. Appreciate your work!
