### ISSUE TITLE
Error loading old save

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-Tapeline#16]
![20201024152039_1](https://user-images.githubusercontent.com/61344188/97081708-d9893a80-160c-11eb-8494-6c00ebb821b7.jpg)

Happens on save load. Full angel bob mods

**Comment by raiguard** [comment]
Please provide the save file!

**Comment by raiguard** [comment]
Please provide the save file!

**Comment by danyax** [comment]
https://yadi.sk/d/yOG5SVOjLqXMIQ?w=1

Please load mod set from attached link. Factorio latest version. Same folder contains savefile 009.zip which cause error on loading. You might need to sync mod startup settings when loading savefile.

**Comment by raiguard** [comment]
Thank you! For future reference, all I need is the save file, not the entire modset. I can use the sync-mods-with-save functionality to automatically download the needed mods. :)

**Comment by raiguard** [comment]
Unfortunately I am completely unable to even load the game with that modset. There are many mods that have conflicts or are just straight-up broken. If you can reproduce the bug with a new save file, please let me know. Sorry!

**Comment by danyax** [comment]
The mod set is definitely valid, I am running it right now. Following steps may help to reproduce configuration. 

1) delete all your mods.
2) load the set I provided. Do not update anything!
3) load savefile with "sync startup setting" option enabled

**Comment by danyax** [comment]
If you provide some error screen of mod conflicts/broken mods, I might help to tell what is wrong in your config

**Comment by raiguard** [comment]
Sorry for the delay, I have reproduced the issue and fixed it. Thank you!
