### ISSUE TITLE
Loading old save

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-Tapeline#17]
I have uploaded earlier save file 009.sav which causes error. After some testing I discovered that error could be reproduced with just one Tapeline mod enabled (disable ALL other mods). Could you please look into this?

**Comment by raiguard** [comment]
No need to open a new issue, I wasn't ignoring you. I'll reply further on the other issue. :)

**Comment by danyax** [comment]
Thanks! Sorry for bugging you, I was not sure are reading comments on closed issues.
