### ISSUE TITLE
a quick way to delete tapes?

### ISSUE THREAD

**Issue by oconnor663** [raiguard/Factorio-Tapeline#18]
If I turn off auto-delete (which I won't do from now on), I find it cumbersome to delete tapes. As far as I can tell, the actions required to delete a tape are:

1. Alt-M
2. shift scroll
3. click the tape
4. double click the trash button

Is there a way to shorten that to just "right click the tape" or something similar? I'm probably missing something simple.

**Comment by raiguard** [comment]
Unfortunately, using other mouse buttons (or even modifier keys!) is impossible. The way that the mod works is that the "Tapeline tool" is actually a disguised grenade that fires super fast, has an infinite range, and never runs out of ammo. The mod works by seeing where that grenade lands. Grenades only support the left mouse button, and there is literally nothing I can do about that.

I do plan on eventually revisiting this mod to give it some much-needed attention, and when I do I'll see about making the deletion process smoother. In my current playthrough I too have been annoyed at the number of click required to delete a tape.

**Comment by oconnor663** [comment]
> a disguised grenade that fires super fast, has an infinite range, and never runs out of ammo

That's awesome though :)

**Comment by NotRexButCaesar** [comment]
Cursor position will be made readable 1.1:

https://forums.factorio.com/viewtopic.php?f=65&t=91098

**Comment by raiguard** [comment]
Yes, but that only works for the initial position. Dragging won't work at all.

**Comment by raiguard** [comment]
In the rewrite of the mod, you will be able to delete tapes by shift + right-clicking them. In fact, the rewrite won't even have a GUI at all! :)

**Comment by oconnor663** [comment]
Woo!

**Comment by raiguard** [comment]
![39dad182-c957-4049-9bd7-12319505c66c](https://user-images.githubusercontent.com/3515394/100286278-c3cea400-2f2f-11eb-8c58-54ddf4c015ec.gif)

Feature complete, except for the gridlines. Those are really difficult so I've been putting them off. :/

**Comment by raiguard** [comment]
This request has been implemented for v2.0.0, so I'm closing this issue!

**Comment by raiguard** [comment]
v2.0.0 has been released!
