### ISSUE TITLE
[2.0.0] Crash when selecting tapeline, then another shortcut, then clearing cursor

### ISSUE THREAD

**Issue by estebanthebad** [raiguard/Factorio-Tapeline#21]
#### Describe the Bug
Crash when selecting tapeline, then another shortcut, then clearing cursor

#### To Reproduce
I am using Tapeline v2.0.0 and Spidertron waypoints v1.7.0
https://mods.factorio.com/mod/SpidertronWaypoints

I think I had a tron remote in hand, but I am not entirely sure.

1. Shortcut "Waypoint mode" (route mode) was selected
2. I misclicked on tapeline
3. I clicked "Patrol mode"
4. I noticed that the icon on hand changed to the tapeline ruler
5. I cleared the cursor with Q
6. Crash

Crash message:
```
The mod Tapeline (2.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Tapeline::on_player_cursor_stack_changed (ID 29)
Given value has to be larger than or equal to: 0
stack traceback:
	[C]: in function '__newindex'
	__Tapeline__/control.lua:299: in function <__Tapeline__/control.lua:279>

```
![tapeline crash](https://user-images.githubusercontent.com/52369117/100491475-153f8480-3124-11eb-96f6-018c75c85de2.jpg)
(Sorry for the cut lower edge. My taskbar is a bit messed up and always in the foreground. That is also the reason why I misclicked. So, good for finding a bug ;-) )

#### Save file & Username
The save file is really huge. Does the description suffice? If not, I can upload the save.

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-Tapeline/files/5609937/factorio-current.log)

**Comment by raiguard** [comment]
I am completely unable to reproduce this. Is it consistently repeatable on that save file? If so, please send it to me, no matter how large it is.

**Comment by estebanthebad** [comment]
I uploaded the save to wetransfer.

https://wetransfer.com/downloads/a60651baeded14382d61c742e6e4db8220201128053742/5ae56d9955df8228ea7cf0336a6a08b020201128053811/8e65c0

link is valid for 2 weeks or something.

Steps to reproduce:
1. Click shortcut for tapeline (without a tron remote)
2. Click "Patrol mode"
3. Clear cursor with Q

Map crashes consistently.

Sidenote: I tried a new freeplay with the same mods (a few are installed) but could not reproduce it there. However, the savegame is a scenario. ComfyFactorio v0.167 ( https://github.com/M3wM3w/ComfyFactorio/wiki ). Sorry, I forgot to mention that. Maybe that is the cause.

**Comment by raiguard** [comment]
Lol, that save file isn't _nearly_ as big as some I've gotten. The largest I've had was around 120 MB. :D

Unfortunately, it looks like Comfy is overriding the increased build distance that Tapeline gives you in order to facilitate the mod's function. I fixed the crash, but there's no way for me to fix the actual issue.

As a result, drawing tapes normally will not work - you will need to shift+draw all of the time. Editing and deleting tapes will continue to work just fine.
