### ISSUE TITLE
Tapeline 2.0.3 error

### ISSUE THREAD

**Issue by bgn68** [raiguard/Factorio-Tapeline#24]
When continuing a saved game the following appears with Tapeline 2.0.3:

Error while running event Tapeline::on_configuration_changed
No character.
stack callback:
[C]: in function '__index'
__Tapeline__/scripts/migration.lua:20: in function 'func'
__flib__/migration.lua:65: in function 'run'
__flib__/migration.lua:87: in function 'on_config_changed'
__Tapeline__/control.lua:82: in function <__Tapeline__/control.lua:81>

I always run in God mode without a character.
The save file size is 76 MB. Even smaller ones that I have are more then 40 MB. If you really need a save file I have to create a new one which needs some time...

Trying to upload the log file results in error: Something went really wrong, and we can't process that file. Try again
Therefore here it is inline:

_edit by maintainer: removed log file since I can reproduce this easily_

**Comment by danyax** [comment]
Same for me. Happens when loading saves with god mode on.

**Comment by raiguard** [comment]
Oops, fixed for the next release.
