### ISSUE TITLE
Biters attack tapeline

### ISSUE THREAD

**Issue by SanderForGodot** [raiguard/Factorio-Tapeline#25]
Drawing a tape line close to biters will make them attack 

1. Go to biter base
2. Make tape line
3. Biters hate it

This issue should be save File and user name unrelated.
I included a small example clip from a fresh Creative world but it also works in survival.

https://user-images.githubusercontent.com/61471064/110696527-7e3a9c00-81eb-11eb-9895-04a4c1e09e61.mp4

**Comment by raiguard** [comment]
Thanks, I added a bittering agent to the Tapelines so the biters won't try to eat them anymore.
