### ISSUE TITLE
Auto clearing tape deletes decorations

### ISSUE THREAD

**Issue by ghost** [raiguard/Factorio-Tapeline#29]
#### Describe the Bug

Auto clearing tape deletes decorations

#### To Reproduce

Drag some tape over decorations like grass or biter base remnants.

#### Save file & Username

https://filetransfer.io/data-package/e9uaGyrB#link
Username is  JackGruff

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-Tapeline/files/8091437/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report. However, this is being caused by RealisticDecorationCleanup. Please report this to the author of that mod.
