### ISSUE TITLE
Tapeline Visible In Map View

### ISSUE THREAD

**Issue by ttyler3** [raiguard/Factorio-Tapeline#30]
#### Is your feature request related to a problem? Please describe.

I would like to use tapeline to measure large distances, such as 5.5km away.

#### Describe the solution you'd like

When using the tapeline tool in the map view (default simple ruler), a line and a human readable number will appear when left-click dragging across the map.

#### Additional context

Current functionality is the tapeline is only visible in the normal view. Yes I acknowledge that in most cases, only people that are playing with fission and fusion weapons would ever need to know large distances such as 5.5km.

**Comment by raiguard** [comment]
I would absolutely love this, but unfortunately it is impossible. Mods can't draw arbitrary things on the chart.
