### ISSUE TITLE
Tapeline Annoyance

### ISSUE THREAD

**Issue by dtoxic47** [raiguard/Factorio-Tapeline#31]
### Description

Tapeline 2.0.9

Placing the "Permanent" tapeline leaves permanent mark in the map view (best i can describe it is like you place pipes and see them in map view) once the tapeline is removed the marks stay in the map view and are not removed

I tried it with all my mods enabled and disabled same thing except if i have enhanced map colors mod the color of the mark changes

P.S
I sent you an email long time ago to that other site where the code was,with pictures and all explanation

### Reproduction

1.Place the "Permanent" tapeline what ever length (longer is easier to see big square is easy to see)
2.Open map view and see tapeline marked on the map (although not exactly like the tapeline drawn,i think it tracks mouse movement somehow
3.remove the tapeline and open the map view again the marks are still there and wont go away. 

Notice the Purple Lines in the Map View that's the problem
 
![Map](https://github.com/raiguard/Tapeline/assets/7866071/7a881e1a-6844-4707-9ecc-e7dd7bec5808)
![Play](https://github.com/raiguard/Tapeline/assets/7866071/d1a9578f-ed9f-4c67-9d9f-cd3b141f2c02)

**Comment by raiguard** [comment]
Sorry for missing the email, since switching back to GitHub I don't really check it any more.

I am unable to reproduce this issue. Could you send me a save file where it is consistently happening?

**Comment by dtoxic47** [comment]
Will do let me just check one more time with all the mods disabled....

**Comment by dtoxic47** [comment]
It's a mod conflict,will try to narrow it down since i have a ton of mods....on it's own it;s not happening,will let you know once i find witch one is it so you can see if you can do something about it

**Comment by dtoxic47** [comment]
Found it...it's Construction Planner,it interferes with your mod since in that mod's ghost's have to be approved by the player i assume you are using some kind of ghost's to draw the tape line?Take a stab at it if you will but ill delete that mod,don't even know how it got into my mod list....anyway sorry for the false alarm

https://mods.factorio.com/mod/ConstructionPlanner

**Comment by raiguard** [comment]
Yeah, ConstructionPlanner is interfering with it and I can't find a way around it on my end. Thanks for the report!

What you're seeing is the internal mechanism of tapeline - a selection tool that also places entities. This is how I get the live position of the cursor while you're dragging.

**Comment by dtoxic47** [comment]
Np,thanks for looking into it
