### ISSUE TITLE
Doesn't work on vanilla/modded concrete

### ISSUE THREAD

**Issue by duckydee** [raiguard/Factorio-Tapeline#34]
### Description

Whenever you try to use tapeline on any non default tile (concrete, bricks, refined concrete, reinforced plate since i'm currently playing krastorio 2, etc.), it shrimply doesn't work. It works just fine on normal tiles, or tiles with concrete that's planned for construction/ghost tiles.

Video of replication on a blank save file:

https://github.com/raiguard/Tapeline/assets/31322692/e1c0a15b-605a-42fd-9af2-7119de508b83

### Reproduction

1. Place down a bunch of concrete
2. Try to measure the distance with tapeline
3. Tapeline doesn't work like normal :(
4. Try to use tapeline on non concrete/brick tiles
5. It'll work just fine
6. why

**Comment by raiguard** [comment]
I cannot reproduce, please provide your save file, or a log file, so I can sync with your modlist.

**Comment by duckydee** [comment]
[factorio-current.log](https://github.com/raiguard/Tapeline/files/15253066/factorio-current.log)
here's a log file.

**Comment by raiguard** [comment]
I still can't reproduce this... it works just fine for me.

Can you upload a save file where this is happening?

**Comment by duckydee** [comment]
the save file used in the video was generated less than a minute ago, it shouldn't be a save thing. and the main file that i'm currently playing on....is over 25MB! so i can't upload that file to gh. i guess i'll just make a random new save and upload that?
[temporary world.zip](https://github.com/raiguard/Tapeline/files/15263649/temporary.world.zip)

**Comment by raiguard** [comment]
Thanks, now I see it. Some other mod is deleting the tapeline internal entity before tapeline can do anything with it, so it doesn't know that you dragged at all.

For some reason updating Krastorio 2 fixes it for me, which makes zero sense. Can you see if updating your mods solves the issue?

**Comment by duckydee** [comment]
yup, updating my mods fixed it! thanks a bunch.

**Comment by raiguard** [comment]
Spooky, glad it works now at least!
