### ISSUE TITLE
Update for 2.0?

### ISSUE THREAD

**Issue by kustkust** [raiguard/Factorio-Tapeline#35]
### Description

Are there any plans for an update to Factorio2.0?

**Comment by raiguard** [comment]
Yes, I am actively working on it. However, the update to 2.0 is involving a complete rewrite of the mod, so it will take a bit longer.

**Comment by Nevrai** [comment]
This is one of my favourite mods. I can’t wait for the update! :)

**Comment by SuperNoodlePlays** [comment]
I can't wait either. How's the progress going so far my dude?

**Comment by Fr-Dae** [comment]
thanks you for your works

**Comment by Hydryad** [comment]
Looking forward to using it to measure out spacing and seeing if I can use quality power poles for a certain task on a certain planet... (avoiding spoilers just in case).

I use so many of your mods and they are invaluable! Slightly off-topic, but having rate calculator updated when I started playing space age was a godsend. Thank you so much!

**Comment by Fr-Dae** [comment]
and in addition, it's more cool than "F5" key

**Comment by ajklotz** [comment]
Here to cheer this on

**Comment by raiguard** [comment]
Tapeline 3.0 has been released!

**Comment by Nevrai** [comment]
Finally! It’s been tough playing without this mod. Thank you, raiguard! 💙
