### ISSUE TITLE
Tutorial prompt permanently stuck on screen

### ISSUE THREAD

**Issue by stucker9** [raiguard/Factorio-Tapeline#4]
http://prntscr.com/qzup5k
The tutorial for tapeline came up when I clicked the shortcut button and gave the prompt and it wont go away so I removed your mod and now this is stuck on my game.

**Comment by raiguard** [comment]
Re-enable the mod and start dragging a tape. That should get rid of the message.

Unfortunately there's literally nothing I can do about it staying after the mod is removed.

If dragging a tape doesn't work, let me know and I'll give you a console command to run.

**Comment by raiguard** [comment]
Did you get it fixed?

**Comment by stucker9** [comment]
Yes sir. Thank you

**Comment by raiguard** [comment]
Awesome!
