### ISSUE TITLE
Tapeline tool replaces RateCalculator selection tool

### ISSUE THREAD

**Issue by m4v** [raiguard/Factorio-Tapeline#40]
### Description

After selecting something with RateCalculator selection tool, Tapeline replaces the tool in cursor. Default mod settings.

### Reproduction

1. Enable both mods Tapeline and RateCalculator
2. Pick RateCalculator tool
3. Select something
4. Tool in cursor is now the Tapeline tool

**Comment by alv666** [comment]
Also happens with the Module Inserter Simplified, even with all tapeline keyboard shortcuts not set.

**Comment by raiguard** [comment]
This was an incredibly rookie mistake. :facepalm:
