### ISSUE TITLE
Error on loading old save

### ISSUE THREAD

**Issue by DmytroBazunov** [raiguard/Factorio-Tapeline#5]
Error while running event Tapeline::on_load()
__Tapeline__/scripts/listeners.lua:41: bad argument #2 of 2 to 'table_size' (table expected, got nil)
stack traceback:
	[C]: in function 'table_size'
	__Tapeline__/scripts/listeners.lua:41: in function 'handler'
	__stdlib__/stdlib/event/event.lua:315: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:335: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:413: in function 'dispatch'
	__stdlib__/stdlib/event/event.lua:78: in function <__stdlib__/stdlib/event/event.lua:77>

**Comment by raiguard** [comment]
That error is happening in a file that doesn't exist anymore. Please upgrade to the newest version.
