### ISSUE TITLE
Crash when changing "Number of tiles per subgrid" below 4

### ISSUE THREAD

**Issue by DerFailer36** [raiguard/Factorio-Tapeline#6]
Hey,
so i tried to change the number of tiles per subgrind by typing in 3 and pressed enter and the game crashed on me. :/
It also crashes with 0. ;)

Error MainLoop.cpp:1202: Exception at tick 29206134: The mod Tapeline (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Tapeline::on_gui_confirmed (ID 141)
__Tapeline__/scripts/util.lua:84: bad argument #1 of 2 to '__newindex' (string expected, got nil)
stack traceback:
	[C]: in function '__newindex'
	__Tapeline__/scripts/util.lua:84: in function 'set_last_valid_value'
	__Tapeline__/scripts/gui/draw.lua:65: in function 'handler'
	__Tapeline__/lualib/event.lua:86: in function <__Tapeline__/lualib/event.lua:26>
5463.823 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Tapeline (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Tapeline::on_gui_confirmed (ID 141)
__Tapeline__/scripts/util.lua:84: bad argument #1 of 2 to '__newindex' (string expected, got nil)
stack traceback:
	[C]: in function '__newindex'
	__Tapeline__/scripts/util.lua:84: in function 'set_last_valid_value'
	__Tapeline__/scripts/gui/draw.lua:65: in function 'handler'
	__Tapeline__/lualib/event.lua:86: in function <__Tapeline__/lualib/event.lua:26>"

**Comment by raiguard** [comment]
Thanks for the report, I'll look into it when I have time.

**Comment by raiguard** [comment]
It's been fixed for the next release. Thank you!
